"""Write db/schema.sql from the ORM models (PostgreSQL dialect).

Why generated: the tables come from the field registry, so the SQL file is
regenerated rather than hand-maintained. Run: python scripts/dump_schema.py
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from sqlalchemy.dialects import postgresql  # noqa: E402
from sqlalchemy.schema import CreateIndex, CreateTable  # noqa: E402

from app import models  # noqa: E402,F401
from app.db import Base  # noqa: E402

out = ["-- AIVOA Deviation Intake Module - PostgreSQL schema",
       "-- GENERATED by backend/scripts/dump_schema.py from app/models.py (field registry).",
       "-- The backend also creates these tables automatically on startup.", ""]
for table in Base.metadata.sorted_tables:
    out.append(str(CreateTable(table, if_not_exists=True).compile(dialect=postgresql.dialect())).strip() + ";\n")
    for idx in table.indexes:
        out.append(str(CreateIndex(idx, if_not_exists=True).compile(dialect=postgresql.dialect())).strip() + ";\n")
target = Path(__file__).resolve().parents[2] / "db" / "schema.sql"
target.write_text("\n".join(out), encoding="utf-8")
print("wrote", target)
