-- AIVOA Deviation Intake Module - PostgreSQL schema
-- GENERATED by backend/scripts/dump_schema.py from app/models.py (field registry).
-- The backend also creates these tables automatically on startup.

CREATE TABLE IF NOT EXISTS deviations (
	id SERIAL NOT NULL, 
	user_overrides JSON NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	last_updated_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	title TEXT, 
	date_detected DATE, 
	reported_by VARCHAR(255), 
	department VARCHAR(255), 
	area_location VARCHAR(255), 
	site VARCHAR(255), 
	product_name VARCHAR(255), 
	batch_number VARCHAR(255), 
	manufacturing_stage VARCHAR(255), 
	equipment_id VARCHAR(255), 
	process_parameter VARCHAR(255), 
	approved_range VARCHAR(255), 
	observed_value VARCHAR(255), 
	description TEXT, 
	immediate_action TEXT, 
	root_cause_hypothesis TEXT, 
	batch_disposition VARCHAR(255), 
	deviation_type VARCHAR(255), 
	category VARCHAR(255), 
	gmp_impact VARCHAR(255), 
	root_cause_category VARCHAR(255), 
	deviation_id VARCHAR(20) NOT NULL, 
	status VARCHAR(255), 
	date_reported DATE, 
	assigned_investigator VARCHAR(255), 
	ha_notification_required VARCHAR(255), 
	customer_notification_required VARCHAR(255), 
	quarantine_reference VARCHAR(255), 
	source_document VARCHAR(255), 
	last_updated_by VARCHAR(255), 
	severity_score INTEGER, 
	occurrence_score INTEGER, 
	detectability_score INTEGER, 
	rpn INTEGER, 
	severity_classification VARCHAR(255), 
	severity_reasoning TEXT, 
	impact_assessment TEXT, 
	suggested_next_action VARCHAR(255), 
	capa_required VARCHAR(255), 
	investigation_due_date DATE, 
	deviation_magnitude VARCHAR(255), 
	repeat_deviation VARCHAR(255), 
	related_deviation_id VARCHAR(255), 
	applicable_sop VARCHAR(255), 
	PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS ix_deviations_deviation_id ON deviations (deviation_id);

CREATE TABLE IF NOT EXISTS deviation_audit (
	id SERIAL NOT NULL, 
	deviation_id VARCHAR(20) NOT NULL, 
	field VARCHAR(64) NOT NULL, 
	old_value TEXT, 
	new_value TEXT, 
	source VARCHAR(40) NOT NULL, 
	instruction TEXT, 
	changed_by VARCHAR(100) NOT NULL, 
	changed_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(deviation_id) REFERENCES deviations (deviation_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS ix_deviation_audit_deviation_id ON deviation_audit (deviation_id);

-- Last record number issued per year; numbers are never reused, even after a deletion.
CREATE TABLE IF NOT EXISTS deviation_sequence (
    year INTEGER PRIMARY KEY,
    last_number INTEGER NOT NULL DEFAULT 0
);
